disk_space:
  path1: "/License_counter/test"
  path2: "/License_counter/end"

cycle: 15

port: 3000
host: '0.0.0.0'

db_path: "folders.db"

db:
  name1:
    uri: "sqlite:///folders.db"
    table: "folders"
  